---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by erik.
--- DateTime: 14-12-19 17:05
---

local e1 = Example()
local e2 = Example()
local e3 = Example()
local e4 = Example()
local e5 = Example()
