---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by erik.
--- DateTime: 14-12-19 17:50
---

example.method1()
local n1 = example.method2()
local n2 = example.method3(2.5, 2.5)
example.method4(0, 0)

return n1 + n2
